### ISSUE TITLE
impl serde::Serialize for Vec1

### ISSUE THREAD

**Issue by eignnx** [1aim/vec1#15]
Hi, I wanted to use this crate, but I'm not sure I can because I need `serde::Serialize` implemented. Any way y'all could impl that trait for `Vec1`? Maybe hide it behind a feature flag so that everyone who uses the crate doesn't need to pull in `serde`?

**Comment by yannleretaille** [comment]
Luckily, there already is a `"serde"` feature flag ☺
Unfortunately, the readme is not mentioning it at the moment, but you can find it in the [docs](https://docs.rs/vec1/1.5.0/vec1/)!

**Comment by eignnx** [comment]
Ahhh, thank you!!! Yeah, that would be great if we could mention that feature in the README. Thanks again!
