### ISSUE TITLE
Support for smallvec

### ISSUE THREAD

**Issue by little-dude** [1aim/vec1#22]
Hey @rustonaut :)

Thanks for the library, it's very useful!

I'd like to have a `vec1` backed by a `SmallVec`. Is this something you'd be willing to support, if I provide the PR? Maybe as an optional feature?

**Comment by rustonaut** [comment]
Sounds good, but give me a moment to think about how to best do it.

**Comment by rustonaut** [comment]
There is an initial implementation in the `smallvec_v1` branch.

But doc still needs to be updated and I will use some macro trick to de-duplicate many methods which
are implemented more or less the same way for `Vec1` and `SmallVec1`.

**Comment by rustonaut** [comment]
Oh and various features of smallvec (no_std, serde, write, const_generics) are not yet directly supported others are internal  only and do not need support but probably should still be re-exported (union, specialization, may_dangle).

**Comment by little-dude** [comment]
Hey :) 

Sorry for the long delay here. I took a look at the `smallvec_v1` branch. It looks good. Anything I can help with?
Regarding the features, I'd need the `serde` one, maybe I can add this as an optional feature?

**Comment by little-dude** [comment]
Oh this is already in the `nightly` branch. Looking at the `Cargo.toml` it looks like enabling `serde` already works.

**Comment by rustonaut** [comment]
Just enable serde on the vec1 create, that makes SmallVec1 serializable.

(Through it doesn't enable smallvec/serde.)

I originally wanted to push a new version to crates.io today but my
computer stoped working (might be easy to fix,idk) so I'm not sure this
will happen today.

**Comment by little-dude** [comment]
No worries regarding the release, I'll fetch the crate from github. Thanks a ton @rustonaut !

**Comment by rustonaut** [comment]
Published new version v1.8.0

Containing `smallvec` support and a lot of other improvements.

**Comment by little-dude** [comment]
Awesome, thanks a lot!
