### ISSUE TITLE
More constructors that guarantee safety

### ISSUE THREAD

**Issue by giarc3** [1aim/vec1#26]
Recently when using this crate I've been writing lots of code that looks like
```rust
let my_vec1: Vec1<_> = my_vec
    .into_iter()
    .chain(std::iter::once(item_to_add))
    .collect_vec()
    .try_into()
    .unwrap();
```
Essentially I want to append an item to a Vec and then turn it into a Vec1. Since I added an item, I know that this is safe, but the `unwrap` doesn't capture this guarantee. 

Would a function for this (and also one that prepends to the Vec) be accepted into the crate?

**Comment by rustonaut** [comment]
I implemented it but I still have to fix the signing & SSH key on my private laptop. Through if nothing gets in the way a v1.9 should be released tomorrow with methods like:

- `Vec1::from_vec_push(std::vec![], 1u8)`
- `Vec1::from_vec_insert(std::vec![1,3], 1, 2u8)`

**Comment by rustonaut** [comment]
Done :tada:

**Comment by giarc3** [comment]
This is fantastic, thank you so much! :tada:
