### ISSUE TITLE
Consider use of NonZeroUsize for methods like truncate

### ISSUE THREAD

**Issue by gliderkite** [1aim/vec1#27]
[Vec1::truncate](https://docs.rs/vec1/latest/vec1/struct.Vec1.html#method.truncate) returns an error if the specified `len: usize` is 0. This could be avoided by having [NonZeroUsize](https://doc.rust-lang.org/stable/std/num/struct.NonZeroUsize.html) instead as input (breaking change).

**Comment by dzmitry-lahoda** [comment]
NonZero so badly integrated into Rust. Are there are compile time/const traits which help with that? Tbh only when NZ will have CONST into it would be awesome.

**Comment by rustonaut** [comment]
Thanks for the interest.

I do not plan to make `truncate` accept non zero for two reasons:

1. in many cases it just moves the non-zero check out of the function, but also no longer yields a `Size0Error`

2. doing so works for `truncate` but not other functions (e.g. `pop`) so making `truncate` fallible is more in line with the rest of the API

Through is will add a variant of the function (and potential other functions, I will have to check) which does accept `NonZeroUsize`.

**Comment by rustonaut** [comment]
I added `truncate_nonzero` and some similar methods in the last release.
