### ISSUE TITLE
Feature request: into_only?

### ISSUE THREAD

**Issue by nyarly** [1aim/vec1#29]
I have a use case where I have a vec1 and it may have exactly one element - in some cases it's an error for there to be more than one element.

Currently I have:
```rust
let mut paths = paths_vec1.into_iter();
if let (path, 0) = (paths.next().expect("vec1"), paths.len()) {
    // Exactly one
    Ok(path)
} else {
    // More than one
    Err(BuildError::output(
        "expected exactly one build output, got more".to_string(),
    ))
}
```

I'd love to have:
```rust
fn into_only(self) -> Option<T>
```
that would consume a vec1 with only one element, but otherwise return None. (Alternatively, it could return a Result with Err(MoreThanOne)). The above would become

```rust
if let Some(path) = paths_vec1.into_only() {
    // Exactly one
    Ok(path)
} else {
    // More than one
    Err(BuildError::output(
        "expected exactly one build output, got more".to_string(),
    ))
}
```

or just

```rust
Ok(paths_vec1.into_only().map_err(|e| Err(BuildError::output("..."))?)
```

**Comment by rustonaut** [comment]
I'm not sure if it isn't too specific for your use case to be added to the library :thinking: .

I have a bit of time in the two weeks starting next week and plan to update my github projects then.  So I will come back to this in 1-2 weeks.

**Comment by rustonaut** [comment]
I thought about it a bit more but I think it's too specific to your use case/out of scope.

You can always add a simple extension trait like

```rust
trait Vec1Ext<T> {
   fn into_only(self) -> Option<T>;
}
impl<T> Vec1Ext<T> for Vec1<T> {
  fn into_only(self) -> Option<T> { 
      ....
  }
}
```

and then e.g. `use crate::utils::Vec1Ext as _`
