### ISSUE TITLE
Add `vec1.nonzero_len()`?

### ISSUE THREAD

**Issue by iago-lito** [1aim/vec1#32]
I guess it would make sense since there is `resize_nonzero` and `truncate_nonzero` + all nonzero arithmetics?

**Comment by rustonaut** [comment]
Makes sense, I added it (but as `.len_nonzero()`). 

(But is not yet published.)

**Comment by iago-lito** [comment]
Cool, cheers :) Is it supposed to be available soon under some release schedule?

**Comment by rustonaut** [comment]
done, though there is no specific schedule.

most times changes only are "needed" after a new rust release added a new methods on `Vec` which takes a `&mut self`
